"""create security events table

Revision ID: 11263ab84241
Revises: f7e4a67557dc
Create Date: 2026-08-12 17:13:08.839489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11263ab84241'
down_revision: Union[str, Sequence[str], None] = 'f7e4a67557dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_destination_ip'), 'security_events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_security_events_event_timestamp'), 'security_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_hostname'), 'security_events', ['hostname'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index('ix_security_events_severity_timestamp', 'security_events', ['severity', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_source'), 'security_events', ['source'], unique=False)
    op.create_index(op.f('ix_security_events_source_ip'), 'security_events', ['source_ip'], unique=False)
    op.create_index('ix_security_events_source_timestamp', 'security_events', ['source', 'event_timestamp'], unique=False)
    op.create_index('ix_security_events_type_timestamp', 'security_events', ['event_type', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_username'), 'security_events', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_username'), table_name='security_events')
    op.drop_index('ix_security_events_type_timestamp', table_name='security_events')
    op.drop_index('ix_security_events_source_timestamp', table_name='security_events')
    op.drop_index(op.f('ix_security_events_source_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_source'), table_name='security_events')
    op.drop_index('ix_security_events_severity_timestamp', table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_hostname'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_destination_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
