"""create playbooks table

Revision ID: 17baecd25d1e
Revises: 9e3ee9dfad73
Create Date: 2026-08-16 06:34:07.772030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17baecd25d1e'
down_revision: Union[str, Sequence[str], None] = '9e3ee9dfad73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('playbook_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_created_at'), 'playbooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_playbooks_created_by_user_id'), 'playbooks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_playbooks_enabled'), 'playbooks', ['enabled'], unique=False)
    op.create_index('ix_playbooks_enabled_created_at', 'playbooks', ['enabled', 'created_at'], unique=False)
    op.create_index(op.f('ix_playbooks_name'), 'playbooks', ['name'], unique=True)
    op.create_index(op.f('ix_playbooks_playbook_type'), 'playbooks', ['playbook_type'], unique=False)
    op.create_index('ix_playbooks_type_enabled', 'playbooks', ['playbook_type', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playbooks_type_enabled', table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_playbook_type'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_name'), table_name='playbooks')
    op.drop_index('ix_playbooks_enabled_created_at', table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_enabled'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_created_by_user_id'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_created_at'), table_name='playbooks')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
