"""add playbook execution actions

Revision ID: 2e36eeea73f3
Revises: 4fa6c0384e91
Create Date: 2026-08-17 12:52:13.853025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e36eeea73f3'
down_revision: Union[str, Sequence[str], None] = '4fa6c0384e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_execution_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('action_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['playbook_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_execution_actions_action_type'), 'playbook_execution_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_playbook_execution_actions_created_at'), 'playbook_execution_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_playbook_execution_actions_execution_id'), 'playbook_execution_actions', ['execution_id'], unique=False)
    op.create_index('ix_playbook_execution_actions_execution_index', 'playbook_execution_actions', ['execution_id', 'action_index'], unique=True)
    op.create_index('ix_playbook_execution_actions_execution_status', 'playbook_execution_actions', ['execution_id', 'status'], unique=False)
    op.create_index(op.f('ix_playbook_execution_actions_status'), 'playbook_execution_actions', ['status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbook_execution_actions_status'), table_name='playbook_execution_actions')
    op.drop_index('ix_playbook_execution_actions_execution_status', table_name='playbook_execution_actions')
    op.drop_index('ix_playbook_execution_actions_execution_index', table_name='playbook_execution_actions')
    op.drop_index(op.f('ix_playbook_execution_actions_execution_id'), table_name='playbook_execution_actions')
    op.drop_index(op.f('ix_playbook_execution_actions_created_at'), table_name='playbook_execution_actions')
    op.drop_index(op.f('ix_playbook_execution_actions_action_type'), table_name='playbook_execution_actions')
    op.drop_table('playbook_execution_actions')
    # ### end Alembic commands ###
