"""create playbook executions table

Revision ID: 4fa6c0384e91
Revises: 17baecd25d1e
Create Date: 2026-08-17 00:11:20.699891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa6c0384e91'
down_revision: Union[str, Sequence[str], None] = '17baecd25d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_executions_alert_id'), 'playbook_executions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_playbook_executions_created_at'), 'playbook_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_playbook_executions_incident_id'), 'playbook_executions', ['incident_id'], unique=False)
    op.create_index('ix_playbook_executions_incident_status', 'playbook_executions', ['incident_id', 'status'], unique=False)
    op.create_index(op.f('ix_playbook_executions_playbook_id'), 'playbook_executions', ['playbook_id'], unique=False)
    op.create_index('ix_playbook_executions_playbook_status', 'playbook_executions', ['playbook_id', 'status'], unique=False)
    op.create_index(op.f('ix_playbook_executions_status'), 'playbook_executions', ['status'], unique=False)
    op.create_index('ix_playbook_executions_status_created_at', 'playbook_executions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_playbook_executions_triggered_by_user_id'), 'playbook_executions', ['triggered_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbook_executions_triggered_by_user_id'), table_name='playbook_executions')
    op.drop_index('ix_playbook_executions_status_created_at', table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_status'), table_name='playbook_executions')
    op.drop_index('ix_playbook_executions_playbook_status', table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_playbook_id'), table_name='playbook_executions')
    op.drop_index('ix_playbook_executions_incident_status', table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_incident_id'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_created_at'), table_name='playbook_executions')
    op.drop_index(op.f('ix_playbook_executions_alert_id'), table_name='playbook_executions')
    op.drop_table('playbook_executions')
    # ### end Alembic commands ###
