"""create detection rules table

Revision ID: 61742ffcebb0
Revises: ae303eb2e01e
Create Date: 2026-08-12 18:57:50.706958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61742ffcebb0'
down_revision: Union[str, Sequence[str], None] = 'ae303eb2e01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_created_by_user_id'), 'detection_rules', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_detection_rules_enabled'), 'detection_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_detection_rules_name'), 'detection_rules', ['name'], unique=True)
    op.create_index(op.f('ix_detection_rules_rule_type'), 'detection_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_detection_rules_severity'), 'detection_rules', ['severity'], unique=False)
    op.create_index('ix_detection_rules_severity_enabled', 'detection_rules', ['severity', 'enabled'], unique=False)
    op.create_index('ix_detection_rules_type_enabled', 'detection_rules', ['rule_type', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_rules_type_enabled', table_name='detection_rules')
    op.drop_index('ix_detection_rules_severity_enabled', table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_severity'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_rule_type'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_name'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_enabled'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_created_by_user_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
