"""create detection matches table

Revision ID: a5405fc900c6
Revises: 34a7dc2dc300
Create Date: 2026-08-12 21:13:31.612098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5405fc900c6'
down_revision: Union[str, Sequence[str], None] = '34a7dc2dc300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_event_id', sa.Integer(), nullable=False),
    sa.Column('detection_rule_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='NEW', nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_rule_id'], ['detection_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_event_id', 'detection_rule_id', name='uq_detection_matches_event_rule')
    )
    op.create_index(op.f('ix_detection_matches_created_at'), 'detection_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_matches_detection_rule_id'), 'detection_matches', ['detection_rule_id'], unique=False)
    op.create_index(op.f('ix_detection_matches_matched_at'), 'detection_matches', ['matched_at'], unique=False)
    op.create_index(op.f('ix_detection_matches_security_event_id'), 'detection_matches', ['security_event_id'], unique=False)
    op.create_index(op.f('ix_detection_matches_severity'), 'detection_matches', ['severity'], unique=False)
    op.create_index('ix_detection_matches_severity_matched_at', 'detection_matches', ['severity', 'matched_at'], unique=False)
    op.create_index(op.f('ix_detection_matches_status'), 'detection_matches', ['status'], unique=False)
    op.create_index('ix_detection_matches_status_matched_at', 'detection_matches', ['status', 'matched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_matches_status_matched_at', table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_status'), table_name='detection_matches')
    op.drop_index('ix_detection_matches_severity_matched_at', table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_severity'), table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_security_event_id'), table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_matched_at'), table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_detection_rule_id'), table_name='detection_matches')
    op.drop_index(op.f('ix_detection_matches_created_at'), table_name='detection_matches')
    op.drop_table('detection_matches')
    # ### end Alembic commands ###
