"""create alerts table

Revision ID: c01134cc5b8a
Revises: b1f8fe7664d0
Create Date: 2026-08-14 15:23:43.309105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01134cc5b8a'
down_revision: Union[str, Sequence[str], None] = 'b1f8fe7664d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_match_id', sa.Integer(), nullable=False),
    sa.Column('security_event_id', sa.Integer(), nullable=False),
    sa.Column('detection_rule_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_match_id'], ['detection_matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['detection_rule_id'], ['detection_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_assigned_status', 'alerts', ['assigned_to_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_assigned_to_user_id'), 'alerts', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_detection_match_id'), 'alerts', ['detection_match_id'], unique=True)
    op.create_index(op.f('ix_alerts_detection_rule_id'), 'alerts', ['detection_rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_opened_at'), 'alerts', ['opened_at'], unique=False)
    op.create_index(op.f('ix_alerts_security_event_id'), 'alerts', ['security_event_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_severity_opened_at', 'alerts', ['severity', 'opened_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_opened_at', 'alerts', ['status', 'opened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_opened_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('ix_alerts_severity_opened_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_security_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_opened_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detection_match_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assigned_to_user_id'), table_name='alerts')
    op.drop_index('ix_alerts_assigned_status', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
